swagger: '2.0'
info:
  title: Example yaml.spec
  description: |
    <a href='https://recordedfuture.com.fake/'><img src='https://hmp.me/dvw4'></a>
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
